#!/usr/bin/env python3
"""
RSI Shadow Mode — Validate strategies before activation.

Runs 10 real evaluations with each candidate strategy,
compares to baseline, and only promotes if ≥10% improvement.

Part of the L3 Autonomous Cycle: detect → generate → shadow → activate.
"""

import json
import logging
import os
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("vsf_rsi.shadow_mode")

# ── Configuration ──────────────────────────────────────────────────
SHADOW_DIR = Path(os.environ.get(
    "RSI_SHADOW_DIR",
    str(Path(__file__).parent.parent.parent / "state" / "shadow")
))
SHADOW_FILE = SHADOW_DIR / "shadow_results.json"

SHADOW_EVALS = 10        # Evaluations per strategy before activation
IMPROVEMENT_THRESHOLD = 0.10  # ≥10% improvement to activate


@dataclass
class StrategyCandidate:
    """A candidate strategy generated by the GA."""
    strategy_id: str
    fault_id: str
    tree: Dict[str, Any]           # Socratic tree structure
    source: str                    # Which predicate/operator this targets
    description: str = ""
    created_at: str = ""


@dataclass
class ShadowResult:
    """Result of shadow evaluation."""
    strategy_id: str
    fault_id: str
    baseline_accuracy: float
    strategy_accuracy: float
    improvement_pct: float
    baseline_latency_ms: float
    strategy_latency_ms: float
    evals_count: int
    passed: bool                   # True if improvement ≥ threshold
    status: str = "pending"        # pending → passed → activated / failed
    activated_at: str = ""
    details: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class ShadowMode:
    """Shadow mode evaluator for L3 strategies.

    Evaluates candidate strategies against a baseline and only
    promotes those that show measurable improvement.
    """

    def __init__(self, engine: Any, metrics: Any = None):
        """
        Args:
            engine: SocraticEngine instance for evaluations
            metrics: RSIMetrics instance (optional, for tracking)
        """
        self.engine = engine
        self.metrics = metrics
        self._results: Dict[str, ShadowResult] = {}
        self._load_results()

    def evaluate_baseline(
        self,
        tree: Any,
        test_cases: List[Dict[str, Any]],
        num_evals: int = SHADOW_EVALS,
    ) -> Tuple[float, float]:
        """Evaluate baseline accuracy and latency for a tree.

        Args:
            tree: Socratic tree to evaluate
            test_cases: List of {tree, ctx} dicts
            num_evals: Number of evaluations to run

        Returns:
            (accuracy, avg_latency_ms)
        """
        correct = 0
        total_latency = 0.0
        count = min(num_evals, len(test_cases))

        for i in range(count):
            tc = test_cases[i % len(test_cases)]
            t_start = time.monotonic()
            try:
                result = self.engine.evaluate(
                    tc.get("tree", tree),
                    tc.get("ctx", {})
                )
                is_true = getattr(result, "is_true", False)
            except Exception:
                is_true = False

            latency = (time.monotonic() - t_start) * 1000.0
            total_latency += latency

            expected = tc.get("expected", False)
            if is_true == expected:
                correct += 1

        accuracy = correct / count if count > 0 else 0.0
        avg_latency = total_latency / count if count > 0 else 0.0

        return accuracy, avg_latency

    def evaluate_strategy(
        self,
        candidate: StrategyCandidate,
        test_cases: List[Dict[str, Any]],
        baseline_accuracy: float,
        baseline_latency: float,
        num_evals: int = SHADOW_EVALS,
    ) -> ShadowResult:
        """Evaluate a candidate strategy against baseline.

        Args:
            candidate: The strategy to evaluate
            test_cases: Test cases to evaluate against
            baseline_accuracy: Baseline accuracy to beat
            baseline_latency: Baseline latency to compare
            num_evals: Number of evaluations

        Returns:
            ShadowResult with pass/fail decision
        """
        # Evaluate strategy
        strategy_correct = 0
        strategy_latency = 0.0
        count = min(num_evals, len(test_cases))

        for i in range(count):
            tc = test_cases[i % len(test_cases)]
            t_start = time.monotonic()
            try:
                result = self.engine.evaluate(
                    candidate.tree,
                    tc.get("ctx", {})
                )
                is_true = getattr(result, "is_true", False)
            except Exception:
                is_true = False

            latency = (time.monotonic() - t_start) * 1000.0
            strategy_latency += latency

            expected = tc.get("expected", False)
            if is_true == expected:
                strategy_correct += 1

        strategy_accuracy = strategy_correct / count if count > 0 else 0.0
        avg_strategy_latency = strategy_latency / count if count > 0 else 0.0

        # Calculate improvement
        if baseline_accuracy > 0:
            improvement = (strategy_accuracy - baseline_accuracy) / baseline_accuracy
        else:
            improvement = strategy_accuracy  # Any accuracy is infinite improvement

        passed = improvement >= IMPROVEMENT_THRESHOLD

        result = ShadowResult(
            strategy_id=candidate.strategy_id,
            fault_id=candidate.fault_id,
            baseline_accuracy=baseline_accuracy,
            strategy_accuracy=strategy_accuracy,
            improvement_pct=improvement,
            baseline_latency_ms=baseline_latency,
            strategy_latency_ms=avg_strategy_latency,
            evals_count=count,
            passed=passed,
            status="passed" if passed else "failed",
            details={
                "tree_op": candidate.tree.get("op", "unknown"),
                "description": candidate.description,
            },
        )

        self._results[candidate.strategy_id] = result
        self._save_results()

        status = "PASSED ✓" if passed else "FAILED ✗"
        logger.info(f"Shadow: {candidate.strategy_id} → {status} "
                    f"(accuracy={strategy_accuracy:.1%}, "
                    f"improvement={improvement:+.1%})")

        return result

    def get_passed_strategies(self) -> List[ShadowResult]:
        """Return strategies that passed shadow evaluation."""
        return [r for r in self._results.values() if r.status == "passed"]

    def get_all_results(self) -> List[ShadowResult]:
        return list(self._results.values())

    def mark_activated(self, strategy_id: str):
        if strategy_id in self._results:
            self._results[strategy_id].status = "activated"
            self._results[strategy_id].activated_at = (
                datetime.now(timezone.utc).isoformat()
            )
            self._save_results()

    def mark_failed(self, strategy_id: str):
        if strategy_id in self._results:
            self._results[strategy_id].status = "failed"
            self._save_results()

    def _load_results(self):
        try:
            if SHADOW_FILE.exists():
                with open(SHADOW_FILE) as f:
                    data = json.load(f)
                for sid, sdata in data.items():
                    self._results[sid] = ShadowResult(**sdata)
        except Exception as e:
            logger.warning(f"Failed to load shadow results: {e}")

    def _save_results(self):
        try:
            SHADOW_DIR.mkdir(parents=True, exist_ok=True)
            with open(SHADOW_FILE, "w") as f:
                json.dump(
                    {sid: r.to_dict() for sid, r in self._results.items()},
                    f, indent=2
                )
        except Exception as e:
            logger.error(f"Failed to save shadow results: {e}")


# ── CLI ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python -m vsf_rsi.rsi_shadow_mode <command>")
        print("Commands:")
        print("  passed  — show strategies that passed shadow")
        print("  all     — show all shadow results")
        sys.exit(1)

    # Load results from file
    shadow = ShadowMode.__new__(ShadowMode)
    shadow._results = {}
    shadow._load_results()

    cmd = sys.argv[1]
    if cmd == "passed":
        results = shadow.get_passed_strategies()
        if not results:
            print("No passed strategies.")
        for r in results:
            print(f"  {r.strategy_id}: accuracy={r.strategy_accuracy:.1%}, "
                  f"improvement={r.improvement_pct:+.1%}")
    elif cmd == "all":
        results = shadow.get_all_results()
        for r in results:
            print(f"  [{r.status}] {r.strategy_id}: "
                  f"accuracy={r.strategy_accuracy:.1%}")
    else:
        print(f"Unknown command: {cmd}")
        sys.exit(1)
