#!/usr/bin/env python3
"""
RSI Advanced Tree Generator — Generates advanced trees
Creates trees with complex logic based on patterns.

RSI LEVEL 3: AUTO-GENERATION
- Generate advanced trees
- Create trees with multiple branches
- Build trees with predicates
- Register in system
"""

import json
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional
from pathlib import Path

# ── Configuration ────────────────────────────────────────────────────
TREES_DIR = Path(__file__).parent.parent.parent.parent / ".opencode" / "plugins" / "support" / "trees"
GENERATED_DIR = TREES_DIR / "generated"
MANIFEST_FILE = Path(__file__).parent.parent / "docs" / "rsi_generated_trees.vsm"


class RSIAdvancedTreeGenerator:
    """Generates advanced trees based on patterns."""
    
    def __init__(self):
        """Initialize advanced tree generator."""
        self.trees_dir = TREES_DIR
        self.generated_dir = GENERATED_DIR
        self.generated_dir.mkdir(parents=True, exist_ok=True)
        
    def generate_advanced_tree(self, pattern: Dict, base_tree: Optional[str] = None) -> str:
        """
        Generate an advanced tree based on pattern.
        
        Args:
            pattern: Detected pattern
            base_tree: Optional base tree to extend
        
        Returns:
            Path to generated tree
        """
        # Generate tree content
        tree_content = self._create_advanced_tree_content(pattern, base_tree)
        
        # Generate filename
        tree_name = pattern.get("name", "auto_generated")
        filename = f"{tree_name}_advanced.tree.vsm"
        filepath = self.generated_dir / filename
        
        # Write tree
        with open(filepath, 'w') as f:
            f.write(tree_content)
        
        # Register in manifest
        self._register_tree(tree_name, filepath, pattern)
        
        return str(filepath)
    
    def _create_advanced_tree_content(self, pattern: Dict, base_tree: Optional[str]) -> str:
        """Create advanced tree content based on pattern."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        tree_name = pattern.get("name", "auto_generated")
        purpose = pattern.get("purpose", "Auto-generated tree")
        
        # Create tree based on template
        if pattern.get("template") == "threshold_optimized_tree":
            return self._create_threshold_optimized_tree(tree_name, purpose, timestamp, pattern)
        elif pattern.get("template") == "coverage_tree":
            return self._create_coverage_tree(tree_name, purpose, timestamp, pattern)
        else:
            return self._create_generic_advanced_tree(tree_name, purpose, timestamp)
    
    def _create_threshold_optimized_tree(self, name: str, purpose: str, timestamp: str, pattern: Dict) -> str:
        """Create threshold optimized tree."""
        best_threshold = pattern.get("best_threshold", 0.7)
        
        return f"""⟦ {name}_advanced | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧

@vsm 1.2
@status active

// ADVANCED TREE: {name}
// Generated: {timestamp}
// Purpose: {purpose}
// Optimized for threshold: {best_threshold}
//
// This tree was auto-generated by RSI Level 3 (Auto-Generation)
// to address threshold optimization needs.

{name}_advanced = decision(
  // Branch 1: High confidence (above threshold + 0.1)
  ctx_equals($ctx, "value", TRUE) → decision(
    ctx_equals($ctx, "value", {best_threshold + 0.1}) → {{ home: "high_confidence", truth: "above optimal threshold", certified: TRUE }},
    TRUE → {{ home: "medium_confidence", truth: "near optimal threshold", certified: TRUE }}
  ),
  
  // Branch 2: Low confidence (below threshold - 0.1)
  ctx_equals($ctx, "value", {best_threshold - 0.1}) → {{ home: "low_confidence", truth: "below optimal threshold", certified: TRUE }},
  
  // Branch 3: Borderline (within 0.05 of threshold)
  ctx_equals($ctx, "value", {best_threshold}) → {{ home: "borderline", truth: "at optimal threshold", certified: TRUE }},
  
  // Default branch
  TRUE → {{ home: "default", truth: "outside optimal range", certified: TRUE }}
)

⟦ /{name}_advanced | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧
"""
    
    def _create_coverage_tree(self, name: str, purpose: str, timestamp: str, pattern: Dict) -> str:
        """Create coverage tree."""
        return f"""⟦ {name}_advanced | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧

@vsm 1.2
@status active

// ADVANCED TREE: {name}
// Generated: {timestamp}
// Purpose: {purpose}
//
// This tree was auto-generated by RSI Level 3 (Auto-Generation)
// to provide coverage for untested thresholds.

{name}_advanced = decision(
  // Branch 1: Very low (0.0 - 0.3)
  ctx_equals($ctx, "value", 0.0) → {{ home: "very_low", truth: "very low value", certified: TRUE }},
  ctx_equals($ctx, "value", 0.15) → {{ home: "very_low", truth: "very low value", certified: TRUE }},
  ctx_equals($ctx, "value", 0.3) → {{ home: "very_low", truth: "very low value", certified: TRUE }},
  
  // Branch 2: Low (0.3 - 0.5)
  ctx_equals($ctx, "value", 0.4) → {{ home: "low", truth: "low value", certified: TRUE }},
  ctx_equals($ctx, "value", 0.5) → {{ home: "low", truth: "low value", certified: TRUE }},
  
  // Branch 3: Medium (0.5 - 0.7)
  ctx_equals($ctx, "value", 0.6) → {{ home: "medium", truth: "medium value", certified: TRUE }},
  ctx_equals($ctx, "value", 0.7) → {{ home: "medium", truth: "medium value", certified: TRUE }},
  
  // Branch 4: High (0.7 - 0.9)
  ctx_equals($ctx, "value", 0.8) → {{ home: "high", truth: "high value", certified: TRUE }},
  ctx_equals($ctx, "value", 0.9) → {{ home: "high", truth: "high value", certified: TRUE }},
  
  // Branch 5: Very high (0.9 - 1.0)
  ctx_equals($ctx, "value", 0.95) → {{ home: "very_high", truth: "very high value", certified: TRUE }},
  ctx_equals($ctx, "value", 1.0) → {{ home: "very_high", truth: "very high value", certified: TRUE }},
  
  // Default branch
  TRUE → {{ home: "default", truth: "value outside expected range", certified: TRUE }}
)

⟦ /{name}_advanced | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧
"""
    
    def _create_generic_advanced_tree(self, name: str, purpose: str, timestamp: str) -> str:
        """Create generic advanced tree."""
        return f"""⟦ {name}_advanced | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧

@vsm 1.2
@status active

// ADVANCED TREE: {name}
// Generated: {timestamp}
// Purpose: {purpose}
//
// This tree was auto-generated by RSI Level 3 (Auto-Generation).

{name}_advanced = decision(
  // Branch 1: Active state
  ctx_equals($ctx, "active", TRUE) → {{ home: "active", truth: "system active", certified: TRUE }},
  
  // Branch 2: Inactive state
  ctx_equals($ctx, "active", FALSE) → {{ home: "inactive", truth: "system inactive", certified: TRUE }},
  
  // Default branch
  TRUE → {{ home: "default", truth: "unknown state", certified: TRUE }}
)

⟦ /{name}_advanced | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧
"""
    
    def _register_tree(self, name: str, filepath: Path, pattern: Dict) -> None:
        """Register tree in manifest."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        
        # Load existing manifest
        manifest = self._load_manifest()
        
        # Add new entry
        manifest["trees"].append({
            "name": name,
            "path": str(filepath),
            "generated": timestamp,
            "pattern_type": pattern.get("type", "unknown"),
            "purpose": pattern.get("purpose", ""),
            "status": "active"
        })
        
        # Save manifest
        self._save_manifest(manifest)
    
    def _load_manifest(self) -> Dict:
        """Load manifest from file."""
        from vsf_rsi.rsi_manifest_parser import load_manifest
        if MANIFEST_FILE.exists():
            return load_manifest(MANIFEST_FILE)
        return {"trees": []}
    
    def _save_manifest(self, manifest: Dict) -> None:
        """Save manifest to file."""
        from vsf_rsi.rsi_manifest_parser import save_manifest
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        save_manifest(MANIFEST_FILE, "trees", manifest["trees"],
                      "rsi_generated_trees", timestamp)
    
    def get_generated_trees(self) -> List[Dict]:
        """Get list of generated trees."""
        manifest = self._load_manifest()
        return manifest.get("trees", [])


# ── CLI Interface ────────────────────────────────────────────────────
def main():
    """CLI interface for RSI advanced tree generator."""
    import argparse
    
    parser = argparse.ArgumentParser(description="RSI Advanced Tree Generator")
    subparsers = parser.add_subparsers(dest="command")
    
    # Generate command
    generate_parser = subparsers.add_parser("generate", help="Generate advanced tree")
    generate_parser.add_argument("name", help="Tree name")
    generate_parser.add_argument("--purpose", default="Auto-generated tree", help="Purpose")
    generate_parser.add_argument("--template", choices=["threshold_optimized", "coverage", "generic"], default="generic", help="Template")
    
    # List command
    subparsers.add_parser("list", help="List generated trees")
    
    args = parser.parse_args()
    generator = RSIAdvancedTreeGenerator()
    
    if args.command == "generate":
        pattern = {
            "name": args.name,
            "purpose": args.purpose,
            "template": f"{args.template}_tree",
            "best_threshold": 0.7
        }
        filepath = generator.generate_advanced_tree(pattern)
        print(f"Generated advanced tree: {filepath}")
    elif args.command == "list":
        trees = generator.get_generated_trees()
        print(f"Generated trees: {len(trees)}")
        for tree in trees:
            print(f"  {tree['name']}: {tree['path']}")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
