#!/usr/bin/env python3
"""
RSI Forest Generator — Generates and manages forests of trees
Forest = Population of trees that evolve over generations.

RSI LEVEL 4: AUTO-EVOLUTION
- Generate initial forests
- Convert genomes to .vsm trees
- Track forest evolution
- Export best trees
"""

import json
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional
from pathlib import Path
from rsi_genetic_algorithm import RSIGeneticAlgorithm, TreeGenome

# ── Configuration ────────────────────────────────────────────────────
FORESTS_DIR = Path(__file__).parent.parent.parent.parent / ".opencode" / "plugins" / "support" / "trees" / "forests"
MANIFEST_FILE = Path(__file__).parent.parent.parent.parent / "docs" / "spec_revision" / "system" / "s1-operations" / "rsi_forests.vsm"


class RSIForestGenerator:
    """Generates and manages forests of trees."""
    
    def __init__(self):
        """Initialize forest generator."""
        self.forests_dir = FORESTS_DIR
        self.forests_dir.mkdir(parents=True, exist_ok=True)
        self.ga = RSIGeneticAlgorithm()
        
    def generate_forest(self, predicate_name: str, population_size: int = 10) -> str:
        """
        Generate a new forest.
        
        Args:
            predicate_name: Name of predicate
            population_size: Number of trees in forest
        
        Returns:
            Path to forest directory
        """
        # Create forest directory
        forest_dir = self.forests_dir / predicate_name
        forest_dir.mkdir(exist_ok=True)
        
        # Generate forest using genetic algorithm
        forest = self.ga.create_forest(predicate_name)
        
        # Convert genomes to .vsm trees
        for genome in forest:
            tree_path = self._genome_to_tree(genome, forest_dir)
            genome.genes["tree_path"] = str(tree_path)
        
        # Save forest metadata
        forest_metadata = {
            "predicate": predicate_name,
            "population_size": len(forest),
            "trees": [
                {
                    "id": g.id,
                    "name": g.name,
                    "fitness": g.fitness,
                    "generation": g.generation,
                    "tree_path": g.genes.get("tree_path", "")
                }
                for g in forest
            ],
            "created": datetime.now(timezone.utc).isoformat()
        }
        
        with open(forest_dir / "forest.json", 'w') as f:
            json.dump(forest_metadata, f, indent=2)
        
        # Register in manifest
        self._register_forest(predicate_name, forest_dir, forest_metadata)
        
        return str(forest_dir)
    
    def _genome_to_tree(self, genome: TreeGenome, output_dir: Path) -> Path:
        """Convert genome to .vsm tree file."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        
        # Build tree content from genome
        branches = genome.genes.get("branches", [])
        
        tree_content = f"""⟦ {genome.name} | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧

@vsm 1.2
@status active

// FOREST TREE: {genome.name}
// Generated: {timestamp}
// Generation: {genome.generation}
// Fitness: {genome.fitness:.4f}
// ID: {genome.id}
//
// This tree was generated by RSI Level 4 (Auto-Evolution)
// as part of a forest (population) for genetic evolution.

{genome.name} = decision(
"""
        
        # Add branches from genome
        for i, branch in enumerate(branches):
            condition = branch.get("condition", "TRUE")
            action = branch.get("action", '{"home": "default", "truth": "default", certified: TRUE}')
            tree_content += f"  // Branch {i + 1}\n"
            tree_content += f"  {condition} → {action},\n"
        
        # Add default branch
        tree_content += f"""  // Default branch
  TRUE → {{ home: "default", truth: "evolved default", certified: TRUE }}
)

⟦ /{genome.name} | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧
"""
        
        # Write tree file
        tree_path = output_dir / f"{genome.name}.tree.vsm"
        with open(tree_path, 'w') as f:
            f.write(tree_content)
        
        return tree_path
    
    def evolve_forest(self, predicate_name: str, generations: int = 10) -> Dict:
        """
        Evolve a forest over multiple generations.
        
        Args:
            predicate_name: Name of predicate
            generations: Number of generations
        
        Returns:
            Evolution results
        """
        # Run genetic algorithm
        result = self.ga.evolve_forest(predicate_name, generations)
        
        # Update forest with evolved trees
        forest_dir = self.forests_dir / predicate_name
        
        if forest_dir.exists():
            # Convert evolved genomes to trees
            for genome in result["final_forest"]:
                tree_path = self._genome_to_tree(genome, forest_dir)
                genome.genes["tree_path"] = str(tree_path)
            
            # Update forest metadata
            forest_metadata = {
                "predicate": predicate_name,
                "population_size": len(result["final_forest"]),
                "trees": [
                    {
                        "id": g.id,
                        "name": g.name,
                        "fitness": g.fitness,
                        "generation": g.generation,
                        "tree_path": g.genes.get("tree_path", "")
                    }
                    for g in result["final_forest"]
                ],
                "evolved": datetime.now(timezone.utc).isoformat(),
                "generations": generations,
                "best_fitness": result["best_tree"].fitness
            }
            
            with open(forest_dir / "forest.json", 'w') as f:
                json.dump(forest_metadata, f, indent=2)
        
        return result
    
    def get_forest(self, predicate_name: str) -> Optional[Dict]:
        """
        Get forest metadata.
        
        Args:
            predicate_name: Name of predicate
        
        Returns:
            Forest metadata or None
        """
        forest_dir = self.forests_dir / predicate_name
        forest_file = forest_dir / "forest.json"
        
        if forest_file.exists():
            with open(forest_file, 'r') as f:
                return json.load(f)
        
        return None
    
    def get_best_tree(self, predicate_name: str) -> Optional[Dict]:
        """
        Get best tree from forest.
        
        Args:
            predicate_name: Name of predicate
        
        Returns:
            Best tree metadata or None
        """
        forest = self.get_forest(predicate_name)
        
        if not forest or not forest.get("trees"):
            return None
        
        # Sort by fitness
        trees = sorted(forest["trees"], key=lambda x: x.get("fitness", 0), reverse=True)
        
        return trees[0] if trees else None
    
    def _register_forest(self, predicate_name: str, forest_dir: Path, metadata: Dict) -> None:
        """Register forest in manifest."""
        timestamp = datetime.now(timezone.utc).isoformat()
        
        # Load existing manifest
        manifest = self._load_manifest()
        
        # Add new entry
        manifest["forests"].append({
            "predicate": predicate_name,
            "path": str(forest_dir),
            "population_size": metadata["population_size"],
            "created": metadata["created"],
            "status": "active"
        })
        
        # Save manifest
        self._save_manifest(manifest)
    
    def _load_manifest(self) -> Dict:
        """Load manifest from file."""
        from rsi_manifest_parser import load_manifest
        if MANIFEST_FILE.exists():
            return load_manifest(MANIFEST_FILE)
        return {"forests": []}
    
    def _save_manifest(self, manifest: Dict) -> None:
        """Save manifest to file."""
        from rsi_manifest_parser import save_manifest
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        save_manifest(MANIFEST_FILE, "forests", manifest["forests"],
                      "rsi_forests", timestamp)
    
    def list_forests(self) -> List[Dict]:
        """List all forests."""
        manifest = self._load_manifest()
        return manifest.get("forests", [])


# ── CLI Interface ────────────────────────────────────────────────────
def main():
    """CLI interface for RSI forest generator."""
    import argparse
    
    parser = argparse.ArgumentParser(description="RSI Forest Generator")
    subparsers = parser.add_subparsers(dest="command")
    
    # Generate command
    generate_parser = subparsers.add_parser("generate", help="Generate forest")
    generate_parser.add_argument("predicate", help="Predicate name")
    generate_parser.add_argument("--population", type=int, default=10, help="Population size")
    
    # Evolve command
    evolve_parser = subparsers.add_parser("evolve", help="Evolve forest")
    evolve_parser.add_argument("predicate", help="Predicate name")
    evolve_parser.add_argument("--generations", type=int, default=10, help="Number of generations")
    
    # Best command
    best_parser = subparsers.add_parser("best", help="Get best tree")
    best_parser.add_argument("predicate", help="Predicate name")
    
    # List command
    subparsers.add_parser("list", help="List forests")
    
    args = parser.parse_args()
    generator = RSIForestGenerator()
    
    if args.command == "generate":
        forest_path = generator.generate_forest(args.predicate, args.population)
        print(f"Generated forest: {forest_path}")
    elif args.command == "evolve":
        result = generator.evolve_forest(args.predicate, args.generations)
        print(f"Evolved forest: {result['generations']} generations")
        print(f"Best fitness: {result['best_tree'].fitness:.4f}")
        print(f"Improvement: {result['improvement']:.4f}")
    elif args.command == "best":
        best = generator.get_best_tree(args.predicate)
        if best:
            print(f"Best tree: {best['name']}")
            print(f"  Fitness: {best['fitness']:.4f}")
            print(f"  Generation: {best['generation']}")
            print(f"  Path: {best['tree_path']}")
        else:
            print("No forest found")
    elif args.command == "list":
        forests = generator.list_forests()
        print(f"Forests: {len(forests)}")
        for forest in forests:
            print(f"  {forest['predicate']}: {forest['population_size']} trees")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
