#!/usr/bin/env python3
"""
RSI Tree Generator — Generates new .vsm trees
Creates modified trees based on detected gaps.

RSI LEVEL 2: AUTO-MODIFICATION
- Generate new trees with modifications
- Add new branches based on gaps
- Create variants for testing
- Register in manifest
"""

import json
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional
from pathlib import Path

# ── Configuration ────────────────────────────────────────────────────
TREES_DIR = Path(__file__).parent.parent.parent.parent / ".opencode" / "plugins" / "support" / "trees"
GENERATED_DIR = TREES_DIR / "generated"
MANIFEST_FILE = Path(__file__).parent.parent.parent.parent / "docs" / "spec_revision" / "system" / "s1-operations" / "rsi_generated_trees.vsm"


class RSITreeGenerator:
    """Generates new .vsm trees based on gaps."""
    
    def __init__(self):
        """Initialize tree generator."""
        self.trees_dir = TREES_DIR
        self.generated_dir = GENERATED_DIR
        self.generated_dir.mkdir(parents=True, exist_ok=True)
        
    def generate_tree(self, predicate_name: str, gaps: Dict, base_tree: Optional[str] = None) -> str:
        """
        Generate a new tree based on gaps.
        
        Args:
            predicate_name: Name of predicate
            gaps: Detected gaps
            base_tree: Optional base tree to modify
        
        Returns:
            Path to generated tree
        """
        # Generate tree content
        tree_content = self._create_tree_content(predicate_name, gaps, base_tree)
        
        # Generate filename
        filename = f"{predicate_name}_auto.tree.vsm"
        filepath = self.generated_dir / filename
        
        # Write tree
        with open(filepath, 'w') as f:
            f.write(tree_content)
        
        # Register in manifest
        self._register_tree(predicate_name, filepath, gaps)
        
        return str(filepath)
    
    def _create_tree_content(self, predicate_name: str, gaps: Dict, base_tree: Optional[str]) -> str:
        """Create tree content based on gaps."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        
        # Analyze gaps to determine modifications
        modifications = self._analyze_gaps(gaps)
        
        # Create tree structure
        tree_content = f"""⟦ {predicate_name}_auto | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧

@vsm 1.2
@status active

// AUTO-GENERATED TREE for {predicate_name}
// Generated: {timestamp}
// Based on gaps: {len(gaps.get('gaps', []))} gaps detected
// 
// This tree was auto-generated by RSI Level 2 (Auto-Modification)
// to address classification gaps.

{predicate_name}_auto = decision(
"""
        
        # Add branches based on modifications
        for i, mod in enumerate(modifications):
            branch = self._create_branch(mod, i)
            tree_content += branch
        
        # Add default branch
        tree_content += f"""  // Default branch
  TRUE → {{ home: "escalate", truth: "auto-generated default", certified: TRUE }}
)

⟦ /{predicate_name}_auto | SOCRATIC-TREE-v1 | vsm-1.2 | {timestamp} ⟧
"""
        
        return tree_content
    
    def _analyze_gaps(self, gaps: Dict) -> List[Dict]:
        """Analyze gaps to determine modifications."""
        modifications = []
        
        for gap in gaps.get("gaps", []):
            if gap["type"] == "low_accuracy":
                modifications.append({
                    "type": "adjust_threshold",
                    "reason": gap.get("suggestion", "Adjust threshold"),
                    "severity": gap.get("severity", "medium")
                })
            
            elif gap["type"] == "threshold_low_accuracy":
                modifications.append({
                    "type": "add_branch",
                    "threshold": gap.get("threshold", 0.5),
                    "reason": gap.get("suggestion", "Add specific branch"),
                    "severity": gap.get("severity", "high")
                })
            
            elif gap["type"] == "insufficient_thresholds":
                modifications.append({
                    "type": "test_thresholds",
                    "reason": gap.get("suggestion", "Test more thresholds"),
                    "severity": gap.get("severity", "medium")
                })
            
            elif gap["type"] == "high_latency":
                modifications.append({
                    "type": "optimize",
                    "reason": gap.get("suggestion", "Optimize logic"),
                    "severity": gap.get("severity", "medium")
                })
        
        return modifications
    
    def _create_branch(self, modification: Dict, index: int) -> str:
        """Create a branch based on modification."""
        if modification["type"] == "adjust_threshold":
            return f"""  // Branch {index + 1}: {modification['reason']}
  ctx_equals($ctx, "adjustment_needed", TRUE) → {{ home: "adjusted", truth: "threshold adjusted", certified: TRUE }},
"""
        
        elif modification["type"] == "add_branch":
            threshold = modification.get("threshold", 0.5)
            return f"""  // Branch {index + 1}: {modification['reason']}
  ctx_equals($ctx, "threshold", {threshold}) → {{ home: "specific", truth: "threshold {threshold} matched", certified: TRUE }},
"""
        
        elif modification["type"] == "test_thresholds":
            return f"""  // Branch {index + 1}: {modification['reason']}
  ctx_has($ctx, "test_mode") → {{ home: "testing", truth: "test mode active", certified: TRUE }},
"""
        
        elif modification["type"] == "optimize":
            return f"""  // Branch {index + 1}: {modification['reason']}
  ctx_equals($ctx, "optimize_mode", TRUE) → {{ home: "optimized", truth: "optimization applied", certified: TRUE }},
"""
        
        return ""
    
    def _register_tree(self, predicate_name: str, filepath: Path, gaps: Dict) -> None:
        """Register tree in manifest."""
        timestamp = datetime.now(timezone.utc).isoformat()
        
        # Load existing manifest
        manifest = self._load_manifest()
        
        # Add new entry
        manifest["trees"].append({
            "predicate": predicate_name,
            "path": str(filepath),
            "generated": timestamp,
            "gaps": len(gaps.get("gaps", [])),
            "status": "active"
        })
        
        # Save manifest
        self._save_manifest(manifest)
    
    def _load_manifest(self) -> Dict:
        """Load manifest from file."""
        from rsi_manifest_parser import load_manifest
        if MANIFEST_FILE.exists():
            return load_manifest(MANIFEST_FILE)
        return {"trees": []}
    
    def _save_manifest(self, manifest: Dict) -> None:
        """Save manifest to file."""
        from rsi_manifest_parser import save_manifest
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        save_manifest(MANIFEST_FILE, "trees", manifest["trees"],
                      "rsi_generated_trees", timestamp)
    
    def get_generated_trees(self) -> List[Dict]:
        """Get list of generated trees."""
        manifest = self._load_manifest()
        return manifest.get("trees", [])


# ── CLI Interface ────────────────────────────────────────────────────
def main():
    """CLI interface for RSI tree generator."""
    import argparse
    
    parser = argparse.ArgumentParser(description="RSI Tree Generator")
    subparsers = parser.add_subparsers(dest="command")
    
    # Generate command
    generate_parser = subparsers.add_parser("generate", help="Generate tree")
    generate_parser.add_argument("predicate", help="Predicate name")
    generate_parser.add_argument("--gaps-file", help="Gaps JSON file")
    
    # List command
    subparsers.add_parser("list", help="List generated trees")
    
    args = parser.parse_args()
    generator = RSITreeGenerator()
    
    if args.command == "generate":
        # Load gaps
        if args.gaps_file:
            with open(args.gaps_file) as f:
                gaps = json.load(f)
        else:
            # Use sample gaps
            gaps = {
                "predicate": args.predicate,
                "gaps": [
                    {"type": "low_accuracy", "severity": "high", "accuracy": 0.65, "suggestion": "Adjust threshold"},
                    {"type": "threshold_low_accuracy", "severity": "high", "threshold": 0.7, "accuracy": 0.6, "suggestion": "Add specific branch"}
                ]
            }
        
        # Generate tree
        filepath = generator.generate_tree(args.predicate, gaps)
        print(f"Generated tree: {filepath}")
    elif args.command == "list":
        trees = generator.get_generated_trees()
        print(f"Generated trees: {len(trees)}")
        for tree in trees:
            print(f"  {tree['predicate']}: {tree['path']}")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
