"""rsi_manifest_parser — parse VSM manifest files for RSI.

design: child/docs/vos_package_detailed_plans.vsm
Parses the VSM manifest format used by rsi_generated_trees.vsm,
rsi_generated_predicates.vsm, rsi_forests.vsm, and rsi_component_registry.json.

Format:
  ⟦ name | MANIFEST-v1 | version | date ⟧
  @vsm version
  @status active
  // comments
  entries = [
    { key: "value", key: "value" },
    ...
  ]
  ⟦ /name ⟧

Usage:
    from rsi_manifest_parser import load_manifest, save_manifest
    manifest = load_manifest(Path("rsi_generated_trees.vsm"))
    # manifest = {"trees": [{"name": "...", "path": "...", ...}, ...]}
"""

import re
from pathlib import Path
from typing import Dict, List, Any


def _parse_entry(line: str) -> Dict[str, str]:
    """Parse a single VSM dict entry line: { key: "value", key: "value" }"""
    entry = {}
    # Match key: "value" or key: number patterns
    for match in re.finditer(r'(\w+):\s*"([^"]*)"', line):
        entry[match.group(1)] = match.group(2)
    for match in re.finditer(r'(\w+):\s*(\d+)', line):
        entry[match.group(1)] = int(match.group(2))
    return entry


def _extract_list_entries(content: str, list_name: str) -> List[Dict[str, str]]:
    """Extract entries from a VSM list: list_name = [ ... ]"""
    # Find the list block
    pattern = rf'{list_name}\s*=\s*\[(.*?)\]'
    match = re.search(pattern, content, re.DOTALL)
    if not match:
        return []

    block = match.group(1)
    entries = []

    for line in block.split('\n'):
        line = line.strip()
        if line.startswith('{') and '}' in line:
            # Extract the dict portion
            dict_match = re.search(r'\{(.*?)\}', line)
            if dict_match:
                entry = _parse_entry(dict_match.group(1))
                if entry:
                    entries.append(entry)

    return entries


def load_manifest(path: Path) -> Dict[str, List[Dict[str, str]]]:
    """Load a VSM manifest file and return its entries.

    Returns a dict where the key is the list name (e.g., "trees", "predicates",
    "forests") and the value is a list of dicts.
    """
    if not path.exists():
        return {}

    content = path.read_text(encoding='utf-8')

    # Find the list name (the first identifier before = [)
    list_match = re.search(r'(\w+)\s*=\s*\[', content)
    if not list_match:
        return {}

    list_name = list_match.group(1)
    entries = _extract_list_entries(content, list_name)

    return {list_name: entries}


def save_manifest(path: Path, list_name: str, entries: List[Dict[str, str]],
                  header_name: str, timestamp: str) -> None:
    """Save entries to a VSM manifest file.

    Args:
        path: Path to the manifest file
        list_name: Name of the list (e.g., "trees", "predicates", "forests")
        entries: List of dicts to serialize
        header_name: Name for the VSM header/footer
        timestamp: UTC timestamp for the header
    """
    content = f"⟦ {header_name} | MANIFEST-v1 | vsm-1.2 | {timestamp} ⟧\n\n"
    content += "@vsm 1.2\n"
    content += "@status active\n\n"
    content += f"// Auto-generated {list_name} manifest\n"
    content += f"// Generated by RSI\n\n"
    content += f"{list_name} = [\n"

    for entry in entries:
        parts = []
        for key, value in entry.items():
            if isinstance(value, int):
                parts.append(f"{key}: {value}")
            else:
                parts.append(f'{key}: "{value}"')
        content += "  { " + ", ".join(parts) + " },\n"

    content += "]\n\n"
    content += f"⟦ /{header_name} ⟧\n"

    path.write_text(content, encoding='utf-8')
